services:
  php:
    build: ./docker/php
    volumes:
      - .:/var/www:delegated
    depends_on:
      - database
    networks:
      - app_network

  nginx:
    build: ./docker/nginx
    ports:
      - "8000:80"
    volumes:
      - ./public:/var/www/public:delegated
    depends_on:
      - php
    networks:
      - app_network

  database:
    image: mariadb:10.7.3
    environment:
      MARIADB_USER: makrosoft
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: makrosoft_db
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: 'no'
    volumes:
      - database_data:/var/lib/mysql:rw
      - ./var/mysql:/var/www/var
    networks:
      - app_network

  adminer:
    image: adminer:latest
    depends_on:
      - database
    environment:
      APP_ENV: dev
      ADMINER_DESIGN: pepa-linha
      ADMINER_DEFAULT_SERVER:
    ports:
      - "8082:8080"
    networks:
      - app_network

networks:
  app_network:

volumes:
  database_data:
